#!/bin/bash
# chkconfig: 2345 20 80
# description: ATF REST service

### BEGN INIT INFO
# Provides testrun
# Required-Start: httpd
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: ATF REST service
### END INIT INFO

DIR=/var/www/cgi-bin/lib
DAEMON=$DIR/launch_service.py
DAEMON_NAME=testrun
DAEMON_OPTS=""
DAEMON_USER=apache
PIDFILE=/var/www/html/htdocs/atf_service.pid
# Source function library.
. /etc/rc.d/init.d/functions
RETVAL=0
prog=launch_service.py
pidfile=/var/www/html/htdocs/launch_service.pid
lockfile=/var/www/html/htdocs/launch_service.lock

do_start() {
        echo -n $"Starting $prog: " |logger -i -t ATF
        pid=$(ps ajx |grep launch_service |grep python |awk '{print $2}')
        if [ -n "$pid" ]; then
                echo -n "$DAEMON_NAME is already running" |logger -i -t ATF
                echo_failure
                echo
                return 1
        fi
        pushd $DIR 2>&1 > /dev/null
        $DAEMON
        RETVAL=$?
        [ $RETVAL -eq 0 ] && touch $lockfile
        [ $RETVAL -eq 0 ] && echo_success
        [ $RETVAL -ne 0 ] && echo_failure
        echo
        return $RETVAL

}

do_stop () {
        echo -n "Stopping $prog: " |logger -i -t ATF
        pid=$(ps ajx |grep launch_service |grep python |awk '{print $2}')
        if [ "$pid" = "" ]; then
                echo -n "$DAEMON_NAME is not running" |logger -i -t ATF
                echo_failure
                echo
                return 1
        fi
        kill -15 `ps ajx |grep launch_service |grep python |awk '{print $2}'` 2>&1 |logger -i -t ATF
        RETVAL=$?
        [ $RETVAL -eq 0 ] && echo_success
        [ $RETVAL -ne 0 ] && echo_failure
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile $pidfile
        return $RETVAL

}

do_status() {
        echo -n "Checking $DAEMON_NAME status: "
        pid=$(ps ajx |grep launch_service |grep python |awk '{print $2}')
        RETVAL=$?
        if [ "$pid" = "" ]; then
                echo "$DAEMON_NAME is not running"
                return 1
        else
                 echo "$DAEMON_NAME is running, process $pid"

        fi
        return $RETVAL
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
        do_${1}
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;

esac
exit 0


